// My Telegram Channel : @Phishingran_Otp - Coded By : @Owner_Phishing

console.clear();

console.log(

"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #D32F2F;font-weight: bold;");